build: off

before_build:
- git clone -q https://github.com/Z3Prover/bin.git Z3Prover
- dir C:\projects\sbv\Z3Prover\nightly
- 7z x C:\projects\sbv\Z3Prover\nightly\z3*x64*win*zip z3_downloaded
- set PATH=C:\projects\sbv\z3_downloaded\bin;%PATH%
- z3 /?
- wget stop here
- curl -ostack.zip -L --insecure http://www.stackage.org/stack/windows-i386
- 7z x stack.zip stack.exe
- stack setup --install-ghc > nul
- stack install cabal-install
- stack exec which ghc
# The following is at best fragile. What happens if ghc version gets updated?
- set PATH=C:\Users\appveyor\AppData\Local\Programs\stack\i386-windows\ghc-8.0.2\bin;C:\Users\appveyor\AppData\Roaming\local\bin;%PATH%


skip_tags: true

build_script:
- cabal update
- cabal install alex
- cabal install happy
- cabal install --only-dependencies --enable-tests --enable-benchmarks
- cabal build
  # - cabal test SBVTest
  # - cabal test SBVDocTest
  # - cabal test SBVHLint
- cabal check
- cabal sdist
